name: Build and Deploy

on:
  push:
  pull_request:
  schedule:
    - cron: 30 * * * *

env:
  ABSORPTIE_NOTION_TOKEN: ${{ secrets.ABSORPTIE_NOTION_TOKEN }}
  ABSORPTIE_NOTION_DATABASE_ID: ${{ secrets.ABSORPTIE_NOTION_DATABASE_ID }}
  ABSORPTIE_NOTION_VERSION: ${{ secrets.ABSORPTIE_NOTION_VERSION }}
  ABSORPTIE_AWS_ACCESS_KEY_ID: ${{ secrets.ABSORPTIE_AWS_ACCESS_KEY_ID }}
  ABSORPTIE_AWS_SECRET_ACCESS_KEY: ${{ secrets.ABSORPTIE_AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: pnpm

      - name: Cache build
        uses: actions/cache@v2
        with:
          path: |
            dist
            node_modules/.absorptie
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build
        run: pnpm build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Cache build
        uses: actions/cache@v2
        with:
          path: |
            dist
            node_modules/.absorptie
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
